### PR TITLE
Fixes to make neutron work with MySQL/MariaDB

### PR DESCRIPTION
**Pull request by albailey**
Some of the SQL syntax added by Wind River does not work with MySQL/MariaDB.
This change updates those schemas so they are compatable in mysql without breaking postgres syntax.
These tests have been verified in a container running with MariaDB.
@Joseph,  please review these changes

### CODE REVIEW

**Comment by dtroyer** [comment]
This looks fine to my non-SQL-expert eyes.  I have asked he team working on the Neutron upstreaming to have a look to as they know this code much better than I do.  I don't expect it to be a problem, mostly I want them to be aware of it and make any adjustments in their work that may be necessary.

**Comment by kailun-qin** [comment]
Thanks for the PR. It makes sense to me.
However, stx-neutron is a staging repo where the changes to OpenStack Neutron will either be upstreamed or be rebased. After checking, I don't think this PR related changes will impact our current upstreaming work. I.e., they may either be dropped or be aligned with upstream Neutron later.

**Comment by dtroyer** [comment]
Thank you Kailun.  Once @joseph chimes in we can merge this.

**Comment by joseph** [comment]
¯\_(ツ)_/¯

**Comment by dtroyer** [comment]
Heh, ok...

**Comment by joseph** [comment]
I did search through your project contributors looking for someone called Joseph, but nada

**Comment by albailey** [comment]
No worries.  It was Joseph Richard.  
Thanks guys.
Al

**Comment by albailey** [comment]
Turns out this breaks something in postgres.  I'll try to figure out why.

**Pull request merged**
