### PR TITLE
OVS w/dpdk support for managed type drivers

### PR DESCRIPTION
**Pull request by mpeters-wrs**

### CODE REVIEW

**Comment by dtroyer** [comment]
Looks like 2 things going on here:

a) I am concerned about adding a new config option, what is the upstream status on this?  Is it another thing we have to deal with there?

b) This looks like a wrs-specific plugin bit, this part LGTM

**Comment by mpeters-wrs** [comment]
a) The new configuration option is required to support the nested virtual environments where OVS is configured to run with a user-space data path (netdev) but cannot support vhost-user ports.  This option permits this override without being specific about executing in a virtual environment.  This would be something that we would want to upstream to provide this flexibility.

b) The managed type drivers was originally a WRS extension and this change would need to be included in any attempts to upstream the overall managed type driver capabilities.

**Comment by dtroyer** [comment]
I would prefer if these were split into 2 PRs since someday someone will have to upstream part of it and they don't appear to be closely related.

Also my note in https://github.com/starlingx-staging/stx-nova/pull/1 about adding to the upstream list applies to a) here too

**Comment by mpeters-wrs** [comment]
I can split this across 2 pull requests.  However, we have large number of backlog items to sync with the staging repositories that I think will be difficult to submit via individual PRs.  I think we need to figure out an efficient way to have multiple commits per PR to enable the backlog items.

**Comment by mpeters-wrs** [comment]
splitting commits across separate pull requests

**Pull request closed without merging**
